---
production: &default
  serverPort: 3333
  baseUrl: http://www.elChatdeAntonio.com
  views:
    engine: .hbs
    extension: .hbs
    layout: main
  html:
    livereload: false
    minify: true
    css:
      stylusPrecompile: true
      compress: true
  languages:
    default: en
    list: [en, es, jp]
  security:
    secret: m4k1ingd3v3lop3ers.com
  session:
    cookieDomain: .makingdevelopers.com
    maxAge: 259200
    cookiePrefix: 'mdSession_'
    path: '/'
    httpOnly: true

stage: &stage
  <<: *default
  baseUrl: http://stage.elChatdeAntonio.com

latest: &latest
  <<: *stage
  baseUrl: http://latest.elChatdeAntonio.com

development:
  <<: *latest
  baseUrl: http://local.elChatdeAntonio.com
  html:
    livereload: true
    minify: false
    css:
      stylusPrecompile: false
      compress: false

